"""Report assembly (Plan §5 Phase 6, §6's suggested report sections).

Takes one or more already-computed `PGxResult` objects for one sample
(optionally already run through `evidence.recommend()` for Tier 2 drug
guidance) and assembles them into the report shape Plan §6 specifies:

  1. Sample and analysis metadata
  2. Gene
  3. Observed relevant variants
  4. Allele/diplotype interpretation
  5. Predicted phenotype
  6. Relevant gene-drug relationships
  7. Guideline source/version (both evidence tiers, separately)
  8. Interpretation notes
  9. Limitations
  10. Technical provenance (license/attribution per §4, all three knowledge sources)

Sections 2-9 are per-gene (one `PGxResult` each); sections 1 and 10 are
report-level, computed once regardless of how many genes are included.

Rendered in the three formats Plan §6 asks for as v1 outputs: JSON
(`to_json`), TSV (`to_tsv`), HTML (`to_html`). PDF is explicitly optional
per the plan and is not built here. Two further formats were added after
Phase 6's initial delivery, at the user's request, as permanent, tested
outputs rather than one-off scripts: Markdown (`to_markdown`, stdlib-only)
and Word (`to_docx`, needs the optional `python-docx` dependency -- see
`pyproject.toml`'s `[project.optional-dependencies].docx` extra). All five
renderers consume the same `_gene_section()` intermediate representation
(the flattened per-gene dict `to_json`/`to_html` already built on) rather
than each re-deriving section content from `PGxResult` independently --
one place to keep the 10 sections' content correct, five ways to render it.

## Deliberately NOT built here

This module does not call any gene function or `evidence.recommend()`
itself, and does not read a VCF. Report assembly is a pure, network-free,
deterministic function of already-computed `PGxResult` objects -- the same
"only Layer 4 touches the network, everything downstream of it doesn't"
principle `evidence.py` established. A caller assembles the `PGxResult`s it
wants included (calling `call_tpmt`/`call_dpyd`/`call_slco1b1`, and
`evidence.recommend()` if drug guidance is wanted) and hands them to
`build_report()`.

## TSV is a summary, not the full report

`to_tsv()` emits one row per gene with only the fields that tabulate
cleanly (diplotype, phenotype, confidence, recommendation). Interpretation
notes, limitations, and technical provenance are prose, not tabular data --
they're only in `to_json()`/`to_html()`. This is a deliberate scope
decision, not an oversight: forcing free-text notes into TSV cells (via
escaping/truncation) would make the TSV harder to read as a table without
making the notes any more accessible than they already are in the other
two formats.

## Limitations text (section 9) is a deliberate, acknowledged duplication

The per-gene limitations below mirror `docs/GENE_SCOPE.md`'s "Known
limitations" sections as of Phase 6 -- GENE_SCOPE.md remains the
authoritative, longer-form source (with citations and rationale); the
short copies here exist so a rendered report is self-contained without
requiring the reader to also have the repo's docs open. Keep the two in
sync by hand when either changes (same duplication-with-acknowledgment
pattern already used between `THIRD_PARTY_DATA.md` and
`docs/DATA_SOURCES_AND_LICENSING.md`). Two limitations GENE_SCOPE.md
previously listed as interim -- TPMT/SLCO1B1's dosage-inferred-phase notes
and DPYD's HapB3 disagreement note each lacking a dedicated field -- were
resolved by this same phase's `interpretation_notes` addition and are
intentionally not repeated here; see GENE_SCOPE.md's Phase 6 update.
"""
from __future__ import annotations

import csv
import html
import io
import json
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Optional

from pgx_interpreter.models import PGxResult

SOFTWARE_DISCLAIMER = (
    "This report is generated by research/educational software. It has not been "
    "independently validated for clinical use and must not be used, alone or in "
    "combination with other information, to make any medical, prescribing, or "
    "treatment decision. See this project's README (\"What this is not\") for the "
    "full scope statement."
)

# Section 9 -- see module docstring for the duplication/acknowledgment note.
_GENE_LIMITATIONS: dict[str, tuple[str, ...]] = {
    "TPMT": (
        "Only 4 variant alleles are recognized (*2, *3A, *3B, *3C), covering "
        "~95% of known TPMT no-function alleles in the population literature; "
        "rarer alleles (*4, *5, *6, *8, and others) are not recognized and fall "
        "through to an unsupported-allele result rather than being silently "
        "mis-called.",
        "Simultaneous variants at both the *2 locus and the *3B/*3C loci at "
        "once are out of scope; reported as an unsupported allele pattern "
        "rather than attempting three-way phasing.",
        "A confident Normal Metabolizer (*1/*1) call requires all three "
        "defining positions (*2, *3B, *3C) confirmed reference; an unconfirmed "
        "*2 locus blocks that specific conclusion even when the *3-family pair "
        "looks clean.",
        "VCF phase information (| separators, phase blocks) is read but not "
        "used by this module's phasing logic.",
        "Multi-allelic ALT fields use only the first listed allele; not "
        "exercised against a genuinely multi-allelic real case yet.",
    ),
    "DPYD": (
        "Only 4 of CPIC's clinically-actionable DPYD loci are recognized "
        "(*2A, *13, D949V, HapB3); rarer variants are not recognized and fall "
        "through to an unsupported-allele result.",
        "Simultaneous variants at more than one of the four independent DPYD "
        "loci at once are out of scope; reported as an unsupported allele "
        "pattern rather than attempting multi-locus phasing.",
        "A confident Normal Metabolizer (*1/*1, activity score 2.0) call "
        "requires all four loci, including both HapB3-defining positions, "
        "confirmed reference.",
        "VCF phase information and multi-allelic ALT fields have the same "
        "limitations documented for TPMT.",
    ),
    "SLCO1B1": (
        "Only 2 of SLCO1B1's ~13 CPIC-classified functional alleles are "
        "implemented (*5, *37, plus their combination *15); increased-function "
        "(*14, *20) and rarer no-function/unknown-function alleles are out of "
        "scope.",
        "\"Possible decreased function\" and \"Increased function\" phenotype "
        "categories can never be produced by this module, since they depend on "
        "alleles it doesn't implement.",
        "VCF phase information and multi-allelic ALT fields have the same "
        "limitations documented for TPMT.",
    ),
    "NUDT15": (
        "Only 1 defining variant (c.415C>T, R139C) is recognized, distinguishing "
        "*1 (normal function) from a consolidated no-function *3 allele; the "
        "GAGTCG-hexanucleotide insertion that further distinguishes PharmVar's "
        "*3.001/*3.002 suballeles (and *6) is out of scope -- correctly "
        "representing that repeat-expansion indel requires a reference FASTA "
        "this project's build environment does not have, and its own literature-"
        "cited rsID (rs869320766) could not be resolved against current dbSNP "
        "(see genes/nudt15.py's module docstring for the real discrepancy found).",
        "\"Possible intermediate metabolizer\" and \"Indeterminate\" phenotype "
        "categories can never be produced by this module, since they depend on "
        "alleles it doesn't implement.",
        "A confident Tier 2 drug recommendation for this gene requires a TPMT "
        "result for the same sample -- CPIC's dosing tables are keyed on the "
        "joint TPMT+NUDT15 phenotype, not NUDT15 alone; see evidence.py's "
        "recommend_compound_thiopurine().",
        "VCF phase information and multi-allelic ALT fields have the same "
        "limitations documented for TPMT (though this module's single-locus "
        "model never has phase to resolve in the first place).",
    ),
}

# Section 10 -- summarizes the real, closed licensing audit in
# docs/DATA_SOURCES_AND_LICENSING.md; not a novel claim made here.
TECHNICAL_PROVENANCE = (
    "This project's own code is licensed MIT. Star-allele definitions "
    "(PharmVar-equivalent) and phenotype/drug-recommendation evidence "
    "(ClinPGx/CPIC) are each licensed CC BY-SA 4.0, with an added "
    "no-commercial-resale condition (from PharmVar and PharmGKB "
    "respectively) that this project's non-commercial, research/educational "
    "use is fully compatible with. No third-party data is bundled in this "
    "software's source; allele definitions and evidence are fetched from "
    "their authoritative sources at run time and cited per gene above "
    "(\"Guideline source/version\"). Full audit: "
    "docs/DATA_SOURCES_AND_LICENSING.md."
)


@dataclass(frozen=True)
class Report:
    """One report: a set of per-gene `PGxResult`s for a single sample, plus
    the report-level metadata (section 1) needed to render it."""

    sample_id: str
    generated_at: str  # ISO 8601 UTC, stamped at build_report() time unless overridden
    results: tuple[PGxResult, ...]


def build_report(
    results: tuple[PGxResult, ...],
    *,
    sample_id: Optional[str] = None,
    generated_at: Optional[str] = None,
) -> Report:
    """Assemble one or more `PGxResult`s (Layers 1-3, optionally with Layer
    4 recommendations attached) into a `Report`.

    `sample_id` is inferred from the results when they all agree (the
    normal case: every result in one report describes the same sample);
    pass it explicitly only to override or to fail loudly if the results
    don't actually share one sample_id (Plan §8: never silently merge data
    that doesn't actually belong together).

    `generated_at` defaults to the current UTC time, but accepts an
    explicit override for reproducible tests/regenerated reports -- same
    reasoning as `evidence.py`'s cache-first, explicitly-stamped design.
    """
    if not results:
        raise ValueError("build_report() requires at least one PGxResult")

    sample_ids = {r.sample_id for r in results}
    if sample_id is None:
        if len(sample_ids) != 1:
            raise ValueError(
                f"results span multiple sample_ids {sorted(sample_ids)}; a report is "
                "for one sample -- pass sample_id explicitly only if this is intentional, "
                "or split results by sample first"
            )
        sample_id = next(iter(sample_ids))
    elif sample_ids != {sample_id}:
        raise ValueError(
            f"sample_id={sample_id!r} does not match the sample_id(s) actually present in "
            f"results: {sorted(sample_ids)}"
        )

    return Report(
        sample_id=sample_id,
        generated_at=generated_at or datetime.now(timezone.utc).isoformat(),
        results=tuple(results),
    )


def _gene_section(result: PGxResult) -> dict:
    """Sections 2-9 for one gene, built from `PGxResult.to_dict()` --
    report.py never reads gene-internal fields directly, only the same
    flattened, schema-validated shape every other consumer sees."""
    d = result.to_dict()
    return {
        "gene": d["gene"],  # section 2
        "genome_build": d["genome_build"],
        "observed_variants": d["observed_variants"],  # section 3
        "allele_diplotype_interpretation": {  # section 4
            "alleles": d["alleles"],
            "diplotype": d["diplotype"],
            "phase_status": d["phase_status"],
            "alternative_diplotypes": d["alternative_diplotypes"],
        },
        "predicted_phenotype": {  # section 5
            "phenotype": d["phenotype"],
            "confidence": d["confidence"],
            "activity_score": d["activity_score"],
        },
        "gene_drug_relationship": {  # section 6
            "drug": d["recommended_drug"],
            "recommendation_category": d["recommendation_category"],
        },
        "guideline_source_version": {  # section 7 -- both evidence tiers, kept separate
            "allele_definition_source": d["allele_definition_source"],
            "allele_definition_version": d["allele_definition_version"],
            "phenotype_evidence_source": d["phenotype_evidence_source"],
            "phenotype_evidence_version": d["phenotype_evidence_version"],
            "recommendation_evidence_source": d["recommendation_evidence_source"],
            "recommendation_evidence_version": d["recommendation_evidence_version"],
            "recommendation_guideline_source": d["recommendation_guideline_source"],
        },
        "interpretation_notes": d["interpretation_notes"],  # section 8
        "limitations": list(_GENE_LIMITATIONS.get(d["gene"], ())),  # section 9
    }


def to_json(report: Report, *, indent: int = 2) -> str:
    payload = {
        "metadata": {  # section 1
            "sample_id": report.sample_id,
            "generated_at": report.generated_at,
            "disclaimer": SOFTWARE_DISCLAIMER,
        },
        "genes": [_gene_section(r) for r in report.results],
        "technical_provenance": TECHNICAL_PROVENANCE,  # section 10
    }
    return json.dumps(payload, indent=indent)


_TSV_FIELDNAMES = [
    "sample_id",
    "gene",
    "genome_build",
    "alleles",
    "diplotype",
    "phase_status",
    "phenotype",
    "confidence",
    "activity_score",
    "recommended_drug",
    "recommendation_category",
]


def to_tsv(report: Report) -> str:
    """One row per gene -- core, tabular fields only. See module docstring
    for why notes/limitations/provenance are deliberately excluded."""
    buf = io.StringIO()
    writer = csv.DictWriter(buf, fieldnames=_TSV_FIELDNAMES, delimiter="\t", lineterminator="\n")
    writer.writeheader()
    for result in report.results:
        d = result.to_dict()
        writer.writerow(
            {
                "sample_id": report.sample_id,
                "gene": d["gene"],
                "genome_build": d["genome_build"],
                "alleles": "/".join(a if a is not None else "?" for a in d["alleles"]),
                "diplotype": d["diplotype"],
                "phase_status": d["phase_status"],
                "phenotype": d["phenotype"],
                "confidence": d["confidence"],
                "activity_score": d["activity_score"] if d["activity_score"] is not None else "",
                "recommended_drug": d["recommended_drug"] or "",
                "recommendation_category": d["recommendation_category"] or "",
            }
        )
    return buf.getvalue()


def _html_escape(value) -> str:
    return html.escape(str(value)) if value is not None else ""


def _html_gene_section(section: dict) -> str:
    variants_rows = "".join(
        f"<tr><td>{_html_escape(v['chrom'])}:{_html_escape(v['pos'])}</td>"
        f"<td>{_html_escape(v['ref'])}&gt;{_html_escape(v['alt'])}</td>"
        f"<td>{_html_escape(v['zygosity'])}</td>"
        f"<td>{_html_escape(v['rsid'])}</td></tr>"
        for v in section["observed_variants"]
    ) or "<tr><td colspan=\"4\"><em>none observed</em></td></tr>"

    alt_diplotypes = ", ".join(section["allele_diplotype_interpretation"]["alternative_diplotypes"]) or "none"
    notes = (
        "<ul>" + "".join(f"<li>{_html_escape(n)}</li>" for n in section["interpretation_notes"]) + "</ul>"
        if section["interpretation_notes"]
        else "<p><em>none</em></p>"
    )
    limitations = "<ul>" + "".join(f"<li>{_html_escape(n)}</li>" for n in section["limitations"]) + "</ul>"

    gdr = section["gene_drug_relationship"]
    drug_line = (
        f"<p><strong>{_html_escape(gdr['drug'])}:</strong> {_html_escape(gdr['recommendation_category'])}</p>"
        if gdr["drug"]
        else "<p><em>no drug recommendation attached to this result</em></p>"
    )

    gsv = section["guideline_source_version"]

    return f"""
    <section class="gene-section">
      <h2>{_html_escape(section['gene'])} <span class="genome-build">({_html_escape(section['genome_build'])})</span></h2>

      <h3>3. Observed relevant variants</h3>
      <table><thead><tr><th>Position</th><th>REF&gt;ALT</th><th>Zygosity</th><th>rsID</th></tr></thead>
      <tbody>{variants_rows}</tbody></table>

      <h3>4. Allele / diplotype interpretation</h3>
      <p><strong>Diplotype:</strong> {_html_escape(section['allele_diplotype_interpretation']['diplotype'])}
      &nbsp;(<strong>phase:</strong> {_html_escape(section['allele_diplotype_interpretation']['phase_status'])})</p>
      <p><strong>Alternative diplotype(s):</strong> {_html_escape(alt_diplotypes)}</p>

      <h3>5. Predicted phenotype</h3>
      <p><strong>{_html_escape(section['predicted_phenotype']['phenotype'])}</strong>
      &nbsp;(confidence: {_html_escape(section['predicted_phenotype']['confidence'])}
      {f", activity score: {_html_escape(section['predicted_phenotype']['activity_score'])}" if section['predicted_phenotype']['activity_score'] is not None else ""})</p>

      <h3>6. Relevant gene-drug relationship(s)</h3>
      {drug_line}

      <h3>7. Guideline source/version</h3>
      <table>
        <tr><th>Allele definitions</th><td>{_html_escape(gsv['allele_definition_source'])} ({_html_escape(gsv['allele_definition_version'])})</td></tr>
        <tr><th>Phenotype evidence (Tier 1)</th><td>{_html_escape(gsv['phenotype_evidence_source'])} ({_html_escape(gsv['phenotype_evidence_version'])})</td></tr>
        <tr><th>Recommendation evidence (Tier 2)</th><td>{_html_escape(gsv['recommendation_evidence_source'] or 'not attached')} ({_html_escape(gsv['recommendation_evidence_version'])})</td></tr>
      </table>

      <h3>8. Interpretation notes</h3>
      {notes}

      <h3>9. Limitations</h3>
      {limitations}
    </section>
    """


_HTML_STYLE = """
    body { font-family: -apple-system, Helvetica, Arial, sans-serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; color: #1a1a1a; }
    .disclaimer { background: #fff3cd; border: 1px solid #d1a94a; border-radius: 6px; padding: 1rem; margin-bottom: 1.5rem; }
    .gene-section { border: 1px solid #ddd; border-radius: 6px; padding: 1rem 1.5rem; margin-bottom: 1.5rem; }
    .genome-build { font-weight: normal; color: #666; font-size: 0.85em; }
    table { border-collapse: collapse; width: 100%; margin: 0.5rem 0; }
    th, td { border: 1px solid #ddd; padding: 0.35rem 0.6rem; text-align: left; font-size: 0.92em; }
    th { background: #f5f5f5; }
    footer { color: #666; font-size: 0.85em; margin-top: 2rem; border-top: 1px solid #ddd; padding-top: 1rem; }
"""


def to_html(report: Report) -> str:
    gene_sections = "".join(_html_gene_section(_gene_section(r)) for r in report.results)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>PGx Interpretation Report — {_html_escape(report.sample_id)}</title>
<style>{_HTML_STYLE}</style>
</head>
<body>
  <h1>PGx Interpretation Report</h1>
  <p><strong>1. Sample:</strong> {_html_escape(report.sample_id)} &nbsp;|&nbsp;
  <strong>Generated:</strong> {_html_escape(report.generated_at)}</p>
  <div class="disclaimer"><strong>Disclaimer:</strong> {_html_escape(SOFTWARE_DISCLAIMER)}</div>

  {gene_sections}

  <footer>
    <h3>10. Technical provenance</h3>
    <p>{_html_escape(TECHNICAL_PROVENANCE)}</p>
  </footer>
</body>
</html>
"""


# --- Markdown (stdlib-only) ---


def _markdown_table(headers: list, rows: list) -> str:
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join(["---"] * len(headers)) + "|"]
    for row in rows:
        cells = ["" if c is None else str(c) for c in row]
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines)


def _markdown_gene_section(section: dict) -> str:
    if section["observed_variants"]:
        variant_rows = [
            [f"{v['chrom']}:{v['pos']}", f"{v['ref']}>{v['alt']}", v["zygosity"], v["rsid"]]
            for v in section["observed_variants"]
        ]
    else:
        variant_rows = [["none observed", "", "", ""]]

    adi = section["allele_diplotype_interpretation"]
    alt_diplotypes = ", ".join(adi["alternative_diplotypes"]) or "none"

    pheno = section["predicted_phenotype"]
    score_part = f", activity score: {pheno['activity_score']}" if pheno["activity_score"] is not None else ""

    gdr = section["gene_drug_relationship"]
    drug_line = (
        f"**{gdr['drug']}:** {gdr['recommendation_category']}"
        if gdr["drug"]
        else "*No drug recommendation attached to this result.*"
    )

    gsv = section["guideline_source_version"]

    notes = (
        "\n".join(f"- {n}" for n in section["interpretation_notes"])
        if section["interpretation_notes"]
        else "*None.*"
    )
    limitations = "\n".join(f"- {n}" for n in section["limitations"])

    return "\n\n".join(
        [
            f"## {section['gene']} ({section['genome_build']})",
            "### 3. Observed relevant variants",
            _markdown_table(["Position", "REF>ALT", "Zygosity", "rsID"], variant_rows),
            "### 4. Allele / diplotype interpretation",
            f"**Diplotype:** {adi['diplotype']} (phase: {adi['phase_status']})  \n"
            f"**Alternative diplotype(s):** {alt_diplotypes}",
            "### 5. Predicted phenotype",
            f"**{pheno['phenotype']}** (confidence: {pheno['confidence']}{score_part})",
            "### 6. Relevant gene-drug relationship(s)",
            drug_line,
            "### 7. Guideline source/version",
            _markdown_table(
                ["", "Source", "Version"],
                [
                    ["Allele definitions", gsv["allele_definition_source"], gsv["allele_definition_version"]],
                    [
                        "Phenotype evidence (Tier 1)",
                        gsv["phenotype_evidence_source"],
                        gsv["phenotype_evidence_version"],
                    ],
                    [
                        "Recommendation evidence (Tier 2)",
                        gsv["recommendation_evidence_source"] or "not attached",
                        gsv["recommendation_evidence_version"],
                    ],
                ],
            ),
            "### 8. Interpretation notes",
            notes,
            "### 9. Limitations",
            limitations,
        ]
    )


def to_markdown(report: Report) -> str:
    """Same 10 sections as `to_html()`, as GitHub-flavored Markdown.
    Stdlib-only -- no dependency beyond the standard library, unlike
    `to_docx()` below."""
    gene_sections = "\n\n---\n\n".join(_markdown_gene_section(_gene_section(r)) for r in report.results)
    return "\n\n".join(
        [
            "# PGx Interpretation Report",
            f"**1. Sample:** {report.sample_id}  \n**Generated:** {report.generated_at}",
            f"> **Disclaimer:** {SOFTWARE_DISCLAIMER}",
            "---",
            gene_sections,
            "---",
            "## 10. Technical provenance",
            TECHNICAL_PROVENANCE,
        ]
    )


# --- Word (.docx) -- needs the optional `python-docx` dependency ---


def _docx_shade_cell(cell, color_hex: str) -> None:
    """python-docx has no high-level cell-shading API; this is the
    standard low-level OOXML technique (add a <w:shd> element to the
    cell's <w:tcPr>) used throughout the python-docx ecosystem for it."""
    from docx.oxml import OxmlElement
    from docx.oxml.ns import qn

    tc_pr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:fill"), color_hex)
    tc_pr.append(shd)


def _docx_add_table(document, headers: list, rows: list):
    table = document.add_table(rows=1, cols=len(headers))
    table.style = "Table Grid"
    for cell, header in zip(table.rows[0].cells, headers):
        cell.text = header
        for paragraph in cell.paragraphs:
            for run in paragraph.runs:
                run.bold = True
        _docx_shade_cell(cell, "EDEDED")
    for row_values in rows:
        cells = table.add_row().cells
        for cell, value in zip(cells, row_values):
            cell.text = "" if value is None else str(value)
    return table


def _docx_add_gene_section(document, section: dict) -> None:
    document.add_heading(f"{section['gene']} ({section['genome_build']})", level=1)

    document.add_heading("3. Observed relevant variants", level=2)
    if section["observed_variants"]:
        rows = [
            [f"{v['chrom']}:{v['pos']}", f"{v['ref']}>{v['alt']}", v["zygosity"], v["rsid"]]
            for v in section["observed_variants"]
        ]
    else:
        rows = [["none observed", "", "", ""]]
    _docx_add_table(document, ["Position", "REF>ALT", "Zygosity", "rsID"], rows)

    adi = section["allele_diplotype_interpretation"]
    document.add_heading("4. Allele / diplotype interpretation", level=2)
    p = document.add_paragraph()
    p.add_run("Diplotype: ").bold = True
    p.add_run(f"{adi['diplotype']} (phase: {adi['phase_status']})")
    alt_diplotypes = ", ".join(adi["alternative_diplotypes"]) or "none"
    document.add_paragraph(f"Alternative diplotype(s): {alt_diplotypes}")

    pheno = section["predicted_phenotype"]
    document.add_heading("5. Predicted phenotype", level=2)
    p = document.add_paragraph()
    p.add_run(pheno["phenotype"]).bold = True
    score_part = f", activity score: {pheno['activity_score']}" if pheno["activity_score"] is not None else ""
    p.add_run(f"  (confidence: {pheno['confidence']}{score_part})")

    gdr = section["gene_drug_relationship"]
    document.add_heading("6. Relevant gene-drug relationship(s)", level=2)
    if gdr["drug"]:
        p = document.add_paragraph()
        p.add_run(f"{gdr['drug']}: ").bold = True
        p.add_run(gdr["recommendation_category"])
    else:
        p = document.add_paragraph()
        p.add_run("No drug recommendation attached to this result.").italic = True

    gsv = section["guideline_source_version"]
    document.add_heading("7. Guideline source/version", level=2)
    _docx_add_table(
        document,
        ["", "Source", "Version"],
        [
            ["Allele definitions", gsv["allele_definition_source"], gsv["allele_definition_version"]],
            ["Phenotype evidence (Tier 1)", gsv["phenotype_evidence_source"], gsv["phenotype_evidence_version"]],
            [
                "Recommendation evidence (Tier 2)",
                gsv["recommendation_evidence_source"] or "not attached",
                gsv["recommendation_evidence_version"],
            ],
        ],
    )

    document.add_heading("8. Interpretation notes", level=2)
    if section["interpretation_notes"]:
        for note in section["interpretation_notes"]:
            document.add_paragraph(note, style="List Bullet")
    else:
        p = document.add_paragraph()
        p.add_run("None.").italic = True

    document.add_heading("9. Limitations", level=2)
    for item in section["limitations"]:
        document.add_paragraph(item, style="List Bullet")


def to_docx(report: Report) -> bytes:
    """Same 10 sections as `to_html()`/`to_markdown()`, as a .docx file,
    returned as bytes (write it to a file yourself -- this function has no
    opinion on where a report ends up on disk, matching the other four
    renderers).

    Requires the optional `python-docx` dependency (`pip install
    pgx-interpretation-pipeline[docx]`, or `pip install python-docx`
    directly) -- imported lazily here so building a JSON/TSV/HTML/Markdown
    report never requires it. Raises a clear `ImportError` with install
    instructions if it isn't available, rather than a bare `ModuleNotFoundError`
    pointing at an internal import line.
    """
    try:
        import docx
    except ImportError as exc:
        raise ImportError(
            "to_docx() requires the optional 'python-docx' package. Install it with "
            "'pip install python-docx' (or the project's [docx] extra) and try again."
        ) from exc

    document = docx.Document()
    document.add_heading("PGx Interpretation Report", level=0)
    p = document.add_paragraph()
    p.add_run(f"1. Sample: {report.sample_id}    Generated: {report.generated_at}")

    disclaimer_table = document.add_table(rows=1, cols=1)
    cell = disclaimer_table.rows[0].cells[0]
    dp = cell.paragraphs[0]
    dp.add_run("Disclaimer: ").bold = True
    dp.add_run(SOFTWARE_DISCLAIMER)
    _docx_shade_cell(cell, "FFF3CD")

    for result in report.results:
        _docx_add_gene_section(document, _gene_section(result))

    document.add_heading("10. Technical provenance", level=1)
    document.add_paragraph(TECHNICAL_PROVENANCE)

    buf = io.BytesIO()
    document.save(buf)
    return buf.getvalue()
